# Generated by Django 5.1.4 on 2025-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('int', 'int'), ('string', 'string')], max_length=32),
        ),
    ]
