# Generated by Django 5.1.4 on 2025-01-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='multiple',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('int', 'int'), ('string', 'string'), ('choices', 'choices'), ('Multiple_choice', 'Multiple_choice')], max_length=32),
        ),
    ]
