# Generated by Django 5.1.4 on 2025-01-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_question_answer_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(default='-', null=True, to='app.answer'),
        ),
    ]
