# Generated by Django 5.1.4 on 2025-01-13 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_answer_question_answers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='past_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
