# Generated by Django 5.1.4 on 2025-01-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_survey_past_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='one_attempt',
            field=models.BooleanField(default=True),
        ),
    ]
