# Generated by Django 5.1.4 on 2025-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category_survey_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='Опрос', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(default='-', to='app.answer'),
        ),
    ]
